# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.IntegerField(default=1)),
                ('c_isselect', models.BooleanField(default=1)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Axf_goods')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel')),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
    ]
