# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_goodscart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderAndGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_orderAndGoods',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_Number', models.CharField(max_length=128)),
                ('o_status', models.IntegerField(default=1)),
                ('o_createTime', models.DateField(auto_now=True)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.UserModel')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.AddField(
            model_name='orderandgood',
            name='o_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.OrderList'),
        ),
        migrations.AddField(
            model_name='orderandgood',
            name='o_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Axf_goods'),
        ),
    ]
